application: pebble-notes
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /auth.*
  script: auth.application

- url: /
  static_dir: static
