# use --project=pebble-notes for gcloud
runtime: python312

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT main:app

instance_class: F1
automatic_scaling:
  max_instances: 1
